version: 2

models:
  - name: stg_mailchimp_campaign_activities
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: stg_mailchimp_campaign_recipients
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: stg_mailchimp_campaigns
    columns:
      - name: campaign_id
        tests:
          - unique
          - not_null

  - name: stg_mailchimp_lists
    columns:
      - name: list_id
        tests:
          - unique
          - not_null

  - name: stg_mailchimp_members
    columns:
      - name: member_id
        tests:
          - unique
          - not_null